(function(a){
	a.mobiscroll.i18n.ar = {
		rtl:true,
		setText:'workportal-general-button-label-ok',
		cancelText:"workportal-general-button-label-cancel",
		clearText:"workportal-widget-query-form-clear-button",
		selectedText:"workportal-widget-query-form-selected",
		dateFormat:'dd/mm/yy',
		dateOrder:'ddmmyy',
		dayNames:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
		dayNamesShort:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
		dayNamesMin:['S','M','T','W','T','F','S'],
		dayText:"reports-general-day",
		hourText:"workportal-hours",
		minuteText:"bz-rp-sensorsedt-formfield-minute",
		monthNames:['January','February','March','April','May','June','July','August','September','October','November','December'],
		monthNamesShort:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
		monthText:"reports-general-month",
		secText:'ثواني',
		amText:'am',
		pmText:'pm',
		timeFormat:'hh:ii A',
		timeWheels:'hhiiA',
		yearText:"reports-general-year",
		nowText:"render-timeentry-now",
		firstDay:0,
		dateText:"workportal-widget-activity-log-table-details-title-date",
		timeText:"workportal-project-plan-time-title",
		calendarText:"workportal-widget-admin-users-requests-table-titles-date",
		closeText:"workportal-case-dialog-box-close",
		todayText:"workportal-taskfeed-today",
		prevMonthText:'Previous Month',
		nextMonthText:'Next Month',
		prevYearText:'Previous Year',
		nextYearText:'Next Year',
		eventText:"workportal-project-user-event",
		eventsText:"workportal-project-events-title",
		fromText:"workportal-project-plan-action-execute-plan",
		toText:"workportal-widget-admin-users-titles-To-text",
		wholeText:'كامل',
		fractionText:'جزء',
		unitText:'وحدة',
		delimiter:'/',
		decimalSeparator:'.',
		thousandsSeparator:',',
		labels:['Years','Months','Days','Hours','Minutes','Seconds',''],
		labelsShort:['Yrs','Mths','Days','Hrs','Mins','Secs',''],
		startText:"workportal-project-plan-action-execute-plan",
		stopText:'توقف',
		resetText:"workportal-widget-admin-language-widget-reset",
		lapText:'Lap',
		hideText:'إخفاء',
		backText:'الى الخلف',
		undoText:'فك'
	};

	$.mobiscroll.i18n['en'] = $.mobiscroll.i18n['en-US'] = {
		// Core
		rtl: false, // Right to left mode
		setText: 'Set',
		cancelText: 'Cancel',
		clearText: 'Clear',
		selectedText: 'selected',
		// Datetime component
		dateFormat: 'dd/mm/yy',
		dateOrder: 'ddmmyy',
		dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
		dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
		dayNamesMin: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
		dayText: 'Day',
		hourText: 'Hours',
		minuteText: 'Minutes',
		monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
		monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
		monthText: 'Month',
		secText: 'Seconds',
		amText: 'am',
		pmText: 'pm',
		timeFormat: 'hh:ii A',
		timeWheels: 'hhiiA',
		yearText: 'Year',
		nowText: 'Now',
		// Calendar component
		firstDay: 0,
		dateText: 'Date',
		timeText: 'Time',
		calendarText: 'Calendar',
		closeText: 'Close',
		todayText: 'Today',
		prevMonthText: 'Previous Month',
		nextMonthText: 'Next Month',
		prevYearText: 'Previous Year',
		nextYearText: 'Next Year',
		// Event calendar
		eventText: 'event',
		eventsText: 'events',
		// Daterange component
		fromText: 'Start',
		toText: 'End',
		// Measurement components
		wholeText: 'Whole',
		fractionText: 'Fraction',
		unitText: 'Unit',
		// Numad date
		delimiter: '/',
		// Numpad decimal
		decimalSeparator: '.',
		thousandsSeparator: ',',
		// Timer / Timespan component
		labels: ['Years', 'Months', 'Days', 'Hours', 'Minutes', 'Seconds', ''],
		labelsShort: ['Yrs', 'Mths', 'Days', 'Hrs', 'Mins', 'Secs', ''],
		// Timer component
		startText: 'Start',
		stopText: 'Stop',
		resetText: 'Reset',
		lapText: 'Lap',
		hideText: 'Hide',
		// Listview
		backText: 'Back',
		undoText: 'Undo'
	};
})(jQuery);